"
" Vim Configuration
" Modular Vim setup with organized configuration files
"

" Source all configuration modules
source ~/.vim/config/plugins.vim
source ~/.vim/config/settings.vim
source ~/.vim/config/appearance.vim
source ~/.vim/config/keymaps.vim
source ~/.vim/config/abbreviations.vim
source ~/.vim/config/autocmds.vim
source ~/.vim/config/plugin-config.vim