# Import themes
# https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/Cobalt2.toml"
]

live_config_reload = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 12
normal = { family = "MD IO Variable", style = "Regular" }
bold = { family = "MD IO Variable", style = "Bold" }
italic = { family = "MD IO Variable", style = "Italic" }
bold_italic = { family = "MD IO Variable", style = "Bold Italic" }

